#pragma once

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VER_STR_HELPER(x) #x
#define VERSION_STR "v" VER_STR_HELPER(VERSION_MAJOR) "." VER_STR_HELPER(VERSION_MINOR) "." VER_STR_HELPER(VERSION_PATCH)
